## Introduction to Python (Video companion)

#### This notebook accompanies the video at https://www.youtube.com/watch?v=VDoGThKUn3k

To get the most out of this tutorial, it's recommended to watch the video first. Changing parts of the code and seeing how the output changes is a great way to learn from there. 

**The brief annotations below aren't meant to be a comprehensive explanation of the code**

Find examples and help for using numpy at https://docs.scipy.org/doc/numpy/reference/routines.html

In [8]:
import numpy as np

### Create a list as a variable

In [44]:
a_variable = [1,2,3,4]
a_variable

[1, 2, 3, 4]

### Two ways of adding entries to a list

In [45]:
a_variable += [5]
a_variable.append(6)

In [46]:
a_variable

[1, 2, 3, 4, 5, 6]

### Convert a list to a numpy array

In [47]:
a_different_variable = np.array(a_variable)
a_different_variable

array([1, 2, 3, 4, 5, 6])

### Perform calculations on each entry of an array

In [48]:
a_different_variable*10

array([10, 20, 30, 40, 50, 60])

In [49]:
(a_different_variable**2 + a_different_variable*6 + 7)**2

array([ 196,  529, 1156, 2209, 3844, 6241])

In [50]:
messy_calculation = (np.sin(a_different_variable) + np.cos(a_different_variable)**2 + np.log(a_different_variable) + np.exp(a_different_variable))

In [51]:
messy_calculation

array([   3.85167939,    9.1646789 ,   22.30535436,   55.65489188,
        149.14413698,  405.86306444])

### Finding the mean and standard deviation of an array

In [52]:
np.mean(messy_calculation),np.std(messy_calculation)

(107.66396765918506, 142.07594429143552)

### Generating arrays 

In [53]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [54]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [55]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

### Examples of accessing values in an array by index

In [56]:
data = 2* np.arange(51)
data

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [57]:
data[5]

10

In [23]:
data

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [24]:
data[2]

4

In [25]:
data[len(data) - 1]

100

In [26]:
data[-1]

100

### Using slicing to take a specific part of an array

data[start:end:step]

In [27]:
data[:5]

array([0, 2, 4, 6, 8])

In [28]:
data[1:5]

array([2, 4, 6, 8])

In [29]:
data[1:5:2]

array([2, 6])

In [30]:
data

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [31]:
data[-2:]

array([ 98, 100])

### Using for loops

for [thing] in [list/array]:

    [do stuff]

In [33]:
sentence = 'Is energy conserved on the cosmological scale?'.split()
sentence

['Is', 'energy', 'conserved', 'on', 'the', 'cosmological', 'scale?']

In [34]:
for word in sentence:
    print(word)
    print()

Is

energy

conserved

on

the

cosmological

scale?



In [35]:
means = []

highest = 1001
batch_size = 100

loops = 200

In [36]:
for i in np.arange(loops):
    
    values = np.random.choice(highest,batch_size)
    average = np.mean(values)
    
    means += [average]

In [42]:
print(len(means))

#the first five values of means
means[:5]

200


[470.85000000000002,
 507.83999999999997,
 529.77999999999997,
 485.51999999999998,
 468.45999999999998]

In [43]:
np.mean(means),np.std(means)

(503.75075000000004, 29.443559328612089)

### Basics of while loops

while [something true]:
    
    [run stuff]

In [58]:
x = 3

while x < 6:
    print(x)
    print(x**2)
    print()
    
    x += 1


3
9

4
16

5
25



In [59]:
total = 0

i = 0

while total < 100:
    total += i
    
    i += 1

In [60]:
total, i

(105, 15)

### if statements

In [61]:
if np.random.choice(101) < 50:
    print('Heads')
else:
    print('Tails')

Tails


### Functions

In [ ]:
def function_name(input1, input2, ..., inputn):
    [do stuff]
    return outputs

In [72]:
def hello():
    return 'Hello'

In [73]:
hello()

'Hello'

In [76]:
hello()

'Hello'

In [77]:
def is_odd(number):
    if np.abs(number) % 2 == 1:
        return True
    else:
        return False

In [80]:
is_odd(0)

False