In [1]:
import numpy as np

In [2]:
a_variable = [1,2,3,4]
a_variable

[1, 2, 3, 4]

In [3]:
a_variable += [5]
a_variable.append(6)

In [4]:
a_variable

[1, 2, 3, 4, 5, 6]

In [5]:
a_different_variable = np.array(a_variable)
a_different_variable

array([1, 2, 3, 4, 5, 6])

In [6]:
a_different_variable*10

array([10, 20, 30, 40, 50, 60])

In [8]:
(a_different_variable**2 + a_different_variable*6 + 7)**2

array([ 196,  529, 1156, 2209, 3844, 6241])

In [9]:
messy_calculation = (np.sin(a_different_variable) + np.cos(a_different_variable)**2 + np.log(a_different_variable) + np.exp(a_different_variable))

In [10]:
messy_calculation

array([   3.85167939,    9.1646789 ,   22.30535436,   55.65489188,
        149.14413698,  405.86306444])

In [11]:
np.mean(messy_calculation),np.std(messy_calculation)

(107.66396765918506, 142.07594429143552)

In [12]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [13]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [15]:
data = 2* np.arange(51)
data

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [16]:
data[5]

10

In [17]:
data

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [18]:
data[2]

4

In [20]:
data[len(data) - 1]

100

In [22]:
data[-1]

100

In [ ]:
data[start:end:step]

In [23]:
data[:5]

array([0, 2, 4, 6, 8])

In [25]:
data[1:5]

array([2, 4, 6, 8])

In [28]:
data[1:5:2]

array([2, 6])

In [29]:
data

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [30]:
data[-2:]

array([ 98, 100])

In [ ]:
for [thing] in [list/array]:
    [do stuff]

In [31]:
sentence = 'Is energy conserved on the cosmological scale?'.split()
sentence

['Is', 'energy', 'conserved', 'on', 'the', 'cosmological', 'scale?']

In [32]:
for word in sentence:
    print(word)
    print()

Is

energy

conserved

on

the

cosmological

scale?



In [44]:
means = []

highest = 1001
batch_size = 100

loops = 200

In [45]:
for i in np.arange(loops):
    
    values = np.random.choice(highest,batch_size)
    average = np.mean(values)
    
    means += [average]

In [46]:
means

[516.82000000000005,
 500.47000000000003,
 479.33999999999997,
 466.56,
 528.58000000000004,
 534.34000000000003,
 527.38,
 453.42000000000002,
 504.93000000000001,
 461.76999999999998,
 509.44999999999999,
 506.94,
 522.77999999999997,
 476.52999999999997,
 518.45000000000005,
 520.41999999999996,
 490.50999999999999,
 476.31,
 527.33000000000004,
 462.69999999999999,
 528.58000000000004,
 542.55999999999995,
 461.63,
 504.99000000000001,
 469.92000000000002,
 517.63999999999999,
 506.13999999999999,
 507.19999999999999,
 474.93000000000001,
 509.50999999999999,
 518.09000000000003,
 516.85000000000002,
 519.39999999999998,
 496.88,
 508.91000000000003,
 474.58999999999997,
 458.32999999999998,
 544.0,
 516.17999999999995,
 453.00999999999999,
 467.85000000000002,
 515.35000000000002,
 459.76999999999998,
 477.76999999999998,
 523.14999999999998,
 504.58999999999997,
 508.55000000000001,
 501.16000000000003,
 529.58000000000004,
 458.80000000000001,
 487.93000000000001,
 503.87,
 490.

In [47]:
np.mean(means),np.std(means)

(500.66949999999997, 29.05872008107033)

In [ ]:
while [something true]:
    [run stuff]

In [48]:
x = 3

while x < 6:
    print(x)
    print(x**2)
    print()
    
    x += 1


3
9

4
16

5
25



In [67]:
total = 0

i = 0

while total < 100:
    total += i
    
    i += 1

In [69]:
total, i

(105, 15)

In [71]:
if np.random.choice(101) < 50:
    print('Heads')
else:
    print('Tails')

Tails


In [ ]:
def function_name(input1, input2, ..., inputn):
    [do stuff]
    return outputs

In [72]:
def hello():
    return 'Hello'

In [73]:
hello()

'Hello'

In [76]:
hello()

'Hello'

In [77]:
def is_odd(number):
    if np.abs(number) % 2 == 1:
        return True
    else:
        return False

In [80]:
is_odd(0)

False